language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - develop
  - /^v\d+\.\d+\.\d+$/

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag jumperfly/s3-proxy:latest jumperfly/s3-proxy:develop
    docker push jumperfly/s3-proxy:develop
    fi
